image:
  repository: 033484686218.dkr.ecr.us-west-2.amazonaws.com/retail-store-ui
  tag: "dev-e8f7fd4"
  pullPolicy: Always
imagePullSecrets:
  - name: regcred
resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    memory: 512Mi
app:
  endpoints:
    catalog: http://retail-store-dev-catalog:80
    carts: http://retail-store-dev-cart-carts:80
    orders: http://retail-store-dev-orders:80
    checkout: http://retail-store-dev-checkout:80
